name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - 'sotf-api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: (cd sotf-api/app && yarn)

      - name: Build
        run: (cd sotf-api/app && yarn build)

      - name: Zip
        run: (cd sotf-api/app/build && zip -r ../api.zip .)

      - name: Deploy to AWS
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: sotf-api
          zip_file: sotf-api/app/api.zip
          handler: api/index.handler 
